name: Dormant Developer Users Audit

on:
  schedule:
    - cron: "0 0 31 2 *"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dormant Developer Users Report
        uses: Sandeep-Playground/Dormant-developer-users@v1.0.0
        with:
          github_token: ${{ secrets.ORG_AUDIT_TOKEN }}
          org_names: yubi-migration
          days_inactive_threshold: 90

      - name: Upload dormant users report
        uses: actions/upload-artifact@v4
        with:
          name: dormant-developer-users-report
          path: "*.csv"
